<section>


  <div class="tabs flex justify-center">
    <a id="2" class="tab tab-lg tab-bordered font-fredoka" href="../php/adminpanelFiche.php">fiches</a>
    <a id="3" class="tab tab-lg tab-bordered font-fredoka" href="../php/adminpanelCom.php">Commentaires</a>
    <a id="4" class="tab tab-lg tab-bordered font-fredoka" href="../php/adminpanelUser.php">Liste de comptes</a>
  </div>
</section>

<section>
  <div class="overflow-x-auto">
    <table class="table w-full">
      <thead>
        <tr>
          <th></th>
          <th class="font-fredoka">titre</th>
          <th class="font-fredoka">date</th>
          <th class="font-fredoka">contenu</th>
          <th class="font-fredoka">user</th>
          <th class="font-fredoka">category</th>

        </tr>
      </thead>
      <tbody>

        <?php if (!empty($fiches)) { ?>
          <!-- row 1 -->
          <?php foreach ($fiches as $fiche) { ?>

            <tr class="hover">
              <td></td>
              <td class="font-rubik"><?= $fiche['ftitle']; ?></td>
              <td class="font-rubik"><?= $fiche['DATE']; ?></td>
              <td class="font-rubik"><?= substr($fiche['TEXTEFICHE'], 1, 15); ?></td>
              <td class="font-rubik"><?= $fiche["NOM"] ?> <?= $fiche["PRENOM"] ?></td>
              <td class="font-rubik"><?= $fiche['TITRE'] ?></td>
              <td><button class="btn btn-xs btn-primary font-rubik " ?><a href="">Bannir</a></button><button class="btn btn-xs btn-primary font-rubik">Modérer</button><button class="btn btn-xs btn-primary font-rubik">Modifier</button></td>
            </tr>


          <?php }; ?>


        <?php } else { ?>
          <tr>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
          </tr>

        <?php } ?>
      </tbody>
    </table>
  </div>
</section>