<section>
  <div class="tabs flex justify-center">
    <a id="2" class="tab tab-lg tab-bordered font-fredoka" href="../php/adminpanelFiche.php">fiches</a>
    <a id="3" class="tab tab-lg tab-bordered font-fredoka" href="../../php/adminpanelCom.php">Commentaires</a>
    <a id="4" class="tab tab-lg tab-bordered font-fredoka" href="../../php/adminpanelUser.php">Liste de comptes</a>
  </div>
</section>

<section>
  <div class="overflow-x-auto">
    <table class="table w-full">
      <thead>
        <tr>
          <th></th>
          <th class="font-fredoka">Nom</th>
          <th class="font-fredoka">Prénom</th>

          <th class="font-fredoka">Email</th>
          <th class="font-fredoka">Modification</th>
        </tr>
      </thead>
      <tbody>
        <?php if (!empty($users)) { ?>
          <!-- row 1 -->
          <?php foreach ($users as $user) { ?>


            <tr class="hover">
              <td></td>
              <td class="font-rubik"><?= $user['NOM']; ?></td>
              <td class="font-rubik"><?= $user['PRENOM']; ?></td>
              <td class="font-rubik"><?= $user['MAIL']; ?></td>
              <td><button class="btn btn-xs btn-primary font-rubik " value=<?= $user['IDUSER']; ?>>Bannir</button><button class="btn btn-xs btn-primary font-rubik">Modérer</button><button class="btn btn-xs btn-primary font-rubik">Modifier</button></td>
            </tr>
          <?php }; ?>
        <?php } else { ?>
          <tr>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
            <td class="font-rubik"></td>
          </tr>

        <?php } ?>
      </tbody>
    </table>
  </div>
</section>