
<!--=============== MAIN ===============-->
<section>
    <div class="tabs flex justify-center">
      <a id="1" class="tab tab-lg tab-bordered font-fredoka tab-active" href="./profil.phtml">Mes fiches</a> 
      <a id="2" class="tab tab-lg tab-bordered font-fredoka" href="./profil2.phtml">Mes commentaires</a> 
    </div>
  </section>

  <section>
    <div class="overflow-x-auto">
      <table class="table w-full">
        <thead>
          <tr>
            <th></th>
            <th class="font-fredoka">Titre fiche</th>
            <th class="font-fredoka">date</th>
            <th class="font-fredoka"> Nom</th>
            <th class="font-fredoka">Email</th>
            <th class="font-fredoka">Gestion</th>
          </tr>
        </thead>
        <tbody>
          <!-- row 1 -->
          <?php foreach($fiche as $fiche){ ?>

            
          <tr class="hover">
          <td></td>
          <td class="font-rubik"><?= $fiche['titre']; ?></td>
          <td class="font-rubik"><?= $fiche['date']; ?></td>
          <td class="font-rubik"><?= $fiche['textefiche']; ?></td>
          <!--<td><button class="btn btn-xs btn-primary font-rubik " value=<?= $user['IDUSER']; ?>>Bannir</button><button class="btn btn-xs btn-primary font-rubik">Modérer</button><button class="btn btn-xs btn-primary font-rubik">Modifier</button></td>-->
          </tr>
          <?php }; ?> 
        </tbody>
      </table>
    </div>
  </section>