

<?php foreach($reps as $fiche ){ ?>

        <div class="w-full bg-accent rounded-lg shadow-lg p-12 flex flex-col justify-center items-center">

            <img class="w-8" src="../img/certif.png" alt="verified">
            <br>
            <h2 class="card-title text-white font-rubik">Le problème ?</h2>
            <p class="text-white font-fredoka"><?= $fiche['TITRE']; ?></p>
            <h2 class="card-title text-white pt-16 font-rubik">La solution !</h2>
            <p class="text-white font-fredoka"><?= $fiche['TEXTEFICHE']; ?></p>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" href="#"><path fill="#e11d48" fill-rule="evenodd" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10ZM11 8a1 1 0 1 1 2 0v4a1 1 0 1 1-2 0V8Zm2 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" clip-rule="evenodd"/></svg>
              <a class="text-white font-fredoka" href="#">Signaler le commentaire</a>
              <div class="text-center">
              <p class="text-base text-white font-normal">________________________________________</p>
              <br>
              


              <!--=============== CATEGORIE + PROFIL FICHE ===============-->
              <div class="card-actions mt-6 text-center justify-center">
                <div class="avatar">
                  <div class="w-8 rounded-full">
                    <img src="https://placeimg.com/192/192/people" />
                  </div>
                </div>
                <span class="badge bg-primary font-fredoka"><?= $user->findUserName($fiche['IDUSER']); ?></span>
                <div class="badge badge-outline text-white font-fredoka"><?= $categorie ->recupererUneCategory($fiche['IDCAT']); ?></div>
                <br><br>
                
              </div>
              <a href="./fiche.html"><button class="btn btn-primary mt-4 font-fredoka">voir la fiche</button></a>
        </div>
          

          <?php } ?>