<section>

  <div class="hero min-h-screen" style="background-color: #46a7d6;">
    <div>
      <div>
        <!-- <h1 class="mb-5 text-5xl font-bold">Listes des fiches recherché</h1> -->
      </div>
    </div>
    <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-6">


        <!--=============== FICHE ===============-->

        <?php if (!empty($fiches)) { ?>

          <?php foreach ($fiches as $fiche) { ?>

            <div class="w-full bg-accent rounded-lg shadow-lg p-12 flex flex-col justify-center items-center">

              <img class="w-8" src="../img/certif.png" alt="verified">
              <br>
              <h2 class="card-title text-white font-rubik">Le problème ?</h2>
              <p class="text-white font-fredoka"><?= $fiche['ftitle'] ?></p>
              <h2 class="card-title text-white pt-16 font-rubik">La solution !</h2>
              <p class="text-white font-fredoka"><?= substr($fiche['TEXTEFICHE'], 1, 15); ?></p>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" href="#">
                <path fill="#e11d48" fill-rule="evenodd" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10ZM11 8a1 1 0 1 1 2 0v4a1 1 0 1 1-2 0V8Zm2 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" clip-rule="evenodd" />
              </svg>
              <a class="text-white font-fredoka" href="#">Signaler le commentaire</a>
              <div class="text-center">
                <p class="text-base text-white font-normal">________________________________________</p>
                <br>



                <!--=============== CATEGORIE + PROFIL FICHE ===============-->
                <div class="card-actions mt-6 text-center justify-center">
                  <div class="avatar">
                    <div class="w-8 rounded-full">
                      <img src="https://placeimg.com/192/192/people" />
                    </div>
                  </div>
                  <span class="badge bg-primary font-fredoka"><?= $fiche["NOM"] ?> <?= $fiche["PRENOM"]; ?></span>
                  <div class="badge badge-outline text-white font-fredoka"><?= $fiche['TITRE'] ?></div>
                  <br><br>

                  <!--===============FICHE COM===============-->

                  <div class="w-full bg-base-100 rounded-lg shadow-lg p-12 ">
                    <div class="card-body">
                      <h2 class="card-title font-fredoka">Les Commentaires</h2>
                      <p class="font-rubik">merci pour cette solution <br> 10/11/2022 </p>
                      <div class="flex">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" href="#">
                          <path fill="#e11d48" fill-rule="evenodd" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10ZM11 8a1 1 0 1 1 2 0v4a1 1 0 1 1-2 0V8Zm2 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" clip-rule="evenodd" />
                        </svg>
                        <a class="text-red font-fredoka" href="#">Signaler</a>
                      </div>
                      <p class="text-base text-grey font-normal">____________________________</p>
                    </div>
                  </div>
                  <form action="" method="post">
                    <a><input type="text" name=" text" placeholder="Entrez votre commentaire" class="input input-bordered input-md w-full max-w-xs" /></a>
                    <input type="hidden" name="idfiche" value=<?php $fiche["IDFICHE"] ?>>


                    <br><br>
                    <input class="btn btn-primary font-fredoka" type="submit" value="Entrez votre commentaire">
                  </form>
                </div>
    </section>
  </div>
</section>




<?php } ?>

<?php } else { ?>

  <p>pas de fiche disponible</p>

<?php } ?>