

 <section class="flex items-center h-full p-16 dark: bg-gray-900 dark: text-gray-100">
    <div class="container flex flex-col items-center justify-center px-5 mx-auto my-8">
      <div class="max-w-md text-center">
        <h2 class="mb-8 font-fredoka text-9xl dark:text-gray-600">
          <span class="sr-only">Erreur</span>404
        </h2>
        <p class="text-2xl font-rubik md:text-3xl">Nous sommes désolés, la page que vous avez demandée n'existe pas</p>
        <p class="mt-4 mb-8 darl:text-gray-400">Essayez de faire vos recherche depuis la page d'accueil</p>
        <a href="../index.html"><button class="btn btn-primary font-fredoka">Page d'accueil</button></a>
      </div>
  </section>

