
 <section>
    <div class="hero min-h-screen" style="background-image: url(../img/BgBookIA.png);">
      <section>
        <div>
          <div class="animated-title">
            <div class="text-top">
              <div class="font-fredoka">
                <span>Votre base de</span>
                <span>Connaissance</span>
              </div>
            </div>
            <div class="text-bottom">
              <div class="font-fredoka">SwiftKnowledge</div>
            </div>
          </div>
        </div>
      </section>

      <div class="hero-overlay bg-opacity-0"></div>
      <div class="hero-content text-center text-neutral-content">
        <div class="max-w-md mt-60">
          <p class="mb-5 text-xl font-rubik text-black">Bienvenue sur la base de connaissance de G4, elle permettra à
            vous même
            d'apporter réponse au problème que vous rencontrez.</p>
          <a href="../php/inscription.phtml"><button class="btn btn-primary font-fredoka">Inscription</button></a>
          <a href="../php/authentification.phtml"><button class="btn btn-primary font-fredoka">Connexion</button></a>
        </div>
      </div>
    </div>
  </section>

