<section>
    <form>
          <div class="form-control">
            <div class="input-group justify-center ">
              <input type="text" placeholder="Votre problème" class="input input-bordered input-primary" />
              <select class="select w-full max-w-xs">
                <!-- faire le code pour avoir la liste des catégories qui sont dans la bdd -->
              <?php foreach($categories as $categorie){ ?>
                <option disabled selected>Catégorie</option>
                <option value="<?= $categorie['IDCAT']; ?>"> 
                <?= $categorie['TITRE']; } ?>
              </select>
              <a href="#"><button class="btn btn-square btn-primary"></a>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              </button>
            </div>
          </div>
    </form>



     <!--=============== MAIN ===============-->


  <section>
    <div class="hero min-h-screen" style="background-color: #46a7d6;">
      <div>
        <div>
          <!-- <h1 class="mb-5 text-5xl font-bold">Listes des fiches recherché</h1> -->
        </div>
      </div>
      <section class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-4 py-12">
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 gap-6">

          <!--=============== FICHE ===============-->
          <div class="w-full bg-accent rounded-lg shadow-lg p-12 flex flex-col justify-center items-center">

            <img class="w-8" src="../img/certif.png" alt="verified">
            <br>
            <h2 class="card-title text-white font-rubik">Le problème ?</h2>
            <p class="text-white font-fredoka">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
              excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            <h2 class="card-title text-white pt-16 font-rubik">La solution !</h2>
            <p class="text-white font-fredoka">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
              excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" href="#"><path fill="#e11d48" fill-rule="evenodd" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10ZM11 8a1 1 0 1 1 2 0v4a1 1 0 1 1-2 0V8Zm2 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" clip-rule="evenodd"/></svg>
              <a class="text-white font-fredoka" href="#">Signaler le commentaire</a>
              <div class="text-center">
              <p class="text-base text-white font-normal">________________________________________</p>
              <br>
              <form action="#" method="post">
                <input type="text" placeholder="Entrez votre commentaire" class="input input-bordered input-md w-full max-w-xs" />
              </form>
              

              <!--=============== CATEGORIE + PROFIL FICHE ===============-->
              <div class="card-actions mt-6 text-center justify-center">
                <div class="avatar">
                  <div class="w-8 rounded-full">
                    <img src="https://placeimg.com/192/192/people" />
                  </div>
                </div>
                <span class="badge bg-primary font-fredoka">No1ceTea</span>
                <div class="badge badge-outline text-white font-fredoka">Fashion</div>
                <br><br>
                <div class="flex">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" href="#"><path fill="#e11d48" fill-rule="evenodd" d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10ZM11 8a1 1 0 1 1 2 0v4a1 1 0 1 1-2 0V8Zm2 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z" clip-rule="evenodd"/></svg>
                  <a class="text-white font-fredoka" href="#">Signaler la fiche</a>
                </div>

              </div>

            </div>
          </div>
          <!--=============== FIN FICHE ===============-->

          <!--=============== FICHE ===============-->
          <div class="w-full bg-accent rounded-lg shadow-lg p-12 flex flex-col justify-center items-center">
            <h2 class="card-title text-white font-rubik">Le problème ?</h2>
            <p class="text-white font-fredoka">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
              excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            <h2 class="card-title text-white pt-16 font-rubik">La solution !</h2>
            <p class="text-white font-fredoka">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
              excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
            <div class="text-center">
              <p class="text-base text-white font-normal">________________________________________</p>

              <!--=============== CATEGORIE + PROFIL FICHE ===============-->
              <div class="card-actions mt-6">
                <div class="avatar">
                  <div class="w-8 rounded-full">
                    <img src="https://placeimg.com/192/192/people" />
                  </div>
                </div>
                <span class="badge bg-primary font-fredoka">No1ceTea</span>
                <div class="badge badge-outline text-white font-fredoka">Fashion</div>
              </div>
              <div class="card-actions justify-center mt-4">
                <button class="btn btn-outline btn-secondary">Proposer une autre solution</button> 
              </div>
            </div>
          </div>
          <!--=============== FIN FICHE ===============-->

        </div>
      </section>
    </div>
  </section>
</section>