
	 
 <?php if(!empty($notification)):?>
   <div class="alert alert-warning alert-dismissible fade show" role="alert">
      	<?php echo $notification ?>
   		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <?php endif; ?>
		
		
			
				<div id="login">
			        <h3 class="text-center text-white pt-5">Login form</h3>
			        <div class="container">
			            <div id="login-row" class="row justify-content-center align-items-center">
			                <div id="login-column" class="col-md-6">
			                    <div id="login-box" class="col-md-12">
			                        <form id="login-form" class="form" action="../Controller/MainController.php?choix=verif" method="post">
			                            <h3 class="text-center text-info">register</h3>
                                        <div class="form-group">
			                                <label for="username" class="text-info">nom:</label><br>
			                                <input type="text" name="nom" id="nom" class="form-control">
											<?php 
												if(isset($errorNom)){
												  	echo $errorNom;
												}
											?>
												  
			                            </div>
                                        <div class="form-group">
			                                <label for="username" class="text-info">prenom:</label><br>
			                                <input type="text" name="prenom" id="prenom" class="form-control">
											<?php 
												if(isset($errorPrenom)){
												  	echo $errorPrenom;
												}
											?>
			                            </div>
			                            <div class="form-group">
			                                <label for="username" class="text-info">mail:</label><br>
			                                <input type="text" name="mail" id="mail" class="form-control">
											<?php 
												if(isset($errorMail)){
												  	echo $errorMail;
												}
											?>

			                            </div>
			                            <div class="form-group">
			                                <label for="password" class="text-info">Password:</label><br>
			                                <input type="text" name="password" id="password" class="form-control">
											<?php 
												if(isset($errorPassword)){
												  	echo $errorPassword;
												}
											?>
			                            </div>
                                        <div class="form-group">
			                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
			                            </div>
			                           
			                            
			                        </form>
			                    </div>
			                </div>
			            </div>
			        </div>
				</div>
		
		
		
	  
	  
	</body>
</html>