
	 
   <section>
    <div class="hero min-h-screen" style="background-color: #46a7d6;">
      <div class="hero-content flex-col lg:flex-row-reverse">
        <div class="text-center lg:text-left">
          <h1 class="text-5xl font-fredoka">Inscrivez-vous dès maintenant !</h1>
          <p class="py-6 font-rubik">S'incrire vous permettra d'accéder à ???</p>
        </div>
        <div class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
          <div class="card-body">
            <div class="form-control">
              <label class="label">
                <span class="label-text font-fredoka">Nom</span>
              </label>
              <input type="text" placeholder="Nom" class="input input-bordered" />
            </div>
            <div class="form-control">
              <label class="label">
                <span class="label-text font-fredoka">Prénom</span>
              </label>
              <input type="text" placeholder="prénom" class="input input-bordered" />
            </div>
            <div class="form-control">
              <label class="label">
                <span class="label-text font-fredoka">Pseudo</span>
              </label>
              <input type="text" placeholder="Pseudo" class="input input-bordered" />
            </div>
            <div class="form-control">
              <label class="label">
                <span class="label-text font-fredoka">Email</span>
              </label>
              <input type="text" placeholder="email" class="input input-bordered" />
            </div>

            <div class="form-control">
              <label class="label">
                <span class="label-text font-fredoka">Mot de passe</span>
              </label>
              <input type="text" placeholder="mot de passe" class="input input-bordered" />
            </div>
            <div class="form-control">
              <label class="label">
                <span class="label-text font-fredoka">Confirmer votre mot de passe</span>
              </label>
              <input type="text" placeholder="re-écrire vorte mot de passe" class="input input-bordered" />
            </div>


            <div class="form-control mt-6">
              <button class="btn btn-primary">S'inscrire</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>