<form  action="add_article.php" method="post">
  <fieldset>
    <legend>Nouvelle fiche</legend>
        
    <div class="form-group">
        <label for="formGroupExampleInput">Title</label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="title" name="title">
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Content</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name=content></textarea>
    </div>
    

    <br>
    <input type="submit" name="submit" class="btn btn-info btn-md  ms-1" value="submit"/>
    
    </fieldset>
</form>