
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--=============== CSS ===============-->
  <link rel="stylesheet" href="../dist/output.css">

  <!--=============== FONT ===============-->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@500&family=Rubik:wght@500&display=swap"
    rel="stylesheet">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@500&family=Rubik&display=swap" rel="stylesheet">
  

  <!--=============== TITLE ===============-->
  <link rel="icon" href="../img/YKNoText.png" />
  <title>SwiftKnowledge - Home</title>
</head>

<body>
  <!--=============== HEADER ===============-->
  <header>
    <div class="navbar bg-base-100">
      <div class="navbar-start">
        <div class="dropdown">
          <label tabindex="0" class="btn btn-ghost lg:hidden">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
              stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
            </svg>
          </label>
          <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
            <li><a class="font-fredoka">Item 1</a></li>
            <li><a class="font-fredoka">Item 3</a></li>
          </ul>
        </div>
        <a class="btn btn-ghost normal-case text-xl" href="./index.html"><img class="object-contain w-44"
            src="../img/YKTextBlack.png" alt="icon"></a>
      </div>
      <div class="navbar-center hidden lg:flex">
        <ul class="menu menu-horizontal p-0">
          <li><a class="font-fredoka">Item 1</a></li>
          <li><a class="font-fredoka">Item 2</a></li>
        </ul>
      </div>
      <div class="navbar-end">
        <a href="../php/recher_displayfiche.php"><button class="btn btn-primary flex font-fredoka">Rechercher</button></a>
      </div>
    </div>
  </header>
  <!--=============== MAIN ===============-->
  <?php	
      include $template;
			if(isset($alertConnexionSuccess)){
				echo $alertConnexionSuccess;
			}elseif(isset($alertSuccessRegister)){
        echo $alertSuccessRegister;
      }
	?>
  <!--=============== FOOTER ===============-->
  <footer class="footer p-10 bg-base-100 text-base-content">
    <div>
      <span class="footer-title font-fredoka">Services</span>
      <a class="link link-hover font-rubik">Branding</a>
      <a class="link link-hover font-rubik">Design</a>
      <a class="link link-hover font-rubik">Marketing</a>
      <a class="link link-hover font-rubik">Advertisement</a>
    </div>
    <div>
      <span class="footer-title font-fredoka">Company</span>
      <a class="link link-hover font-rubik">About us</a>
      <a class="link link-hover font-rubik">Contact</a>
      <a class="link link-hover font-rubik">Jobs</a>
      <a class="link link-hover font-rubik">Press kit</a>
    </div>
    <div>
      <span class="footer-title font-fredoka">Legal</span>
      <a class="link link-hover font-rubik">Terms of use</a>
      <a class="link link-hover font-rubik">Privacy policy</a>
      <a class="link link-hover font-rubik">Cookie policy</a>
    </div>
  </footer>
  <footer class="footer px-10 py-4 border-t bg-base-100 text-base-content border-base-300">
    <div class="items-center grid-flow-col">
      <a class="btn btn-ghost normal-case text-xl" href="./index.html"><img class="object-contain w-44"
          src="../img/YKTextBlack.png" alt="icon"></a>
      <p class="font-rubik">SwiftKnowledge. ProtechCompany.<br>Providing reliable tech since 2022</p>
    </div>
    <div class="md:place-self-center md:justify-self-end">
      <div class="grid grid-flow-col gap-4">
        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
            class="fill-current">
            <path
              d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z">
            </path>
          </svg></a>
        <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
            class="fill-current">
            <path
              d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z">
            </path>
          </svg></a>
        <a href="#"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 300 300"
            style="enable-background:new 0 0 300 300;" xml:space="preserve">
            <g id="XMLID_504_">
              <path id="XMLID_505_" d="M38.52,0.012h222.978C282.682,0.012,300,17.336,300,38.52v222.978c0,21.178-17.318,38.49-38.502,38.49
           H38.52c-21.184,0-38.52-17.313-38.52-38.49V38.52C0,17.336,17.336,0.012,38.52,0.012z M218.546,33.329
           c-7.438,0-13.505,6.091-13.505,13.525v32.314c0,7.437,6.067,13.514,13.505,13.514h33.903c7.426,0,13.506-6.077,13.506-13.514
           V46.854c0-7.434-6.08-13.525-13.506-13.525H218.546z M266.084,126.868h-26.396c2.503,8.175,3.86,16.796,3.86,25.759
           c0,49.882-41.766,90.34-93.266,90.34c-51.487,0-93.254-40.458-93.254-90.34c0-8.963,1.37-17.584,3.861-25.759H33.35v126.732
           c0,6.563,5.359,11.902,11.916,11.902h208.907c6.563,0,11.911-5.339,11.911-11.902V126.868z M150.283,90.978
           c-33.26,0-60.24,26.128-60.24,58.388c0,32.227,26.98,58.375,60.24,58.375c33.278,0,60.259-26.148,60.259-58.375
           C210.542,117.105,183.561,90.978,150.283,90.978z" />
          </svg></a>

      </div>
    </div>
  </footer>

</body>

</html>
