<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body class="container-fluid">

    <header>
      <div class="m-5">
         <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{{path('home')}}">Swift knowledge </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="../Controller/MainController.php?choix=inscription">Inscription</a>
                </li>
                 <!--
                <li class="nav-item">
                  <a class="nav-link" href="{{path('profile')}}">Profile</a>
                </li>
                -->
                
                  <li class="nav-item">
                  <a class="nav-link" href="../Controller/MainController.php?choix=connexion">Connexion</a>
                </li>
               
              </ul>
              <div style="margin: auto ; margin-right: 0px;" class="d-flex ">
                <div class="form-inline my-2 my-lg-0">
                  <input class="form-control  mr-sm-2" list="datalistOptions" id="exampleDataList" placeholder="Type to search...">
                  <datalist id="datalistOptions">
                  </datalist>
                </div>
                <!--
                {# affiche conditionnel si utilisateur est connecter #}
                {%  if is_granted('IS_AUTHENTICATED_FULLY') %}
                  <a href='{{path("cart")}}' class=" ml-2 mr-2 btn btn-primary">  Aller  au panier</a>
                  <a href='{{path("app_logout")}} ' class="btn btn-primary"> Deconnection</a>
                {% else %}
                  <a href='{{path("login")}}' class=" ml-2 mr-2 btn btn-primary"> Connection</a>
                  <a href='{{path("app_register")}}' class="btn btn-primary"> S'inscrire</a>
                {% endif %}
                -->
              </div>
            </div>
          </div> 

        </nav>
      </div>
    </header>  
    
    <?php	include $template;	?>

    <footer class="mainfooter" role="contentinfo">
			  <div class="footer-middle">
			  <div class="container">
			    <div class="row">
			      <div class="col-md-3 col-sm-6">
			        <!--Column1-->
			        <div class="footer-pad">
			          <h4>Heading 1</h4>
			          <ul class="list-unstyled">
			            <li><a href="#"></a></li>
			            <li><a href="#">Payment Center</a></li>
			            <li><a href="#">Contact Directory</a></li>
			            <li><a href="#">Forms</a></li>
			            <li><a href="#">News and Updates</a></li>
			            <li><a href="#">FAQs</a></li>
			          </ul>
			        </div>
			      </div>
			      <div class="col-md-3 col-sm-6">
			        <!--Column1-->
			        <div class="footer-pad">
			          <h4>Heading 2</h4>
			          <ul class="list-unstyled">
			            <li><a href="#">Website Tutorial</a></li>
			            <li><a href="#">Accessibility</a></li>
			            <li><a href="#">Disclaimer</a></li>
			            <li><a href="#">Privacy Policy</a></li>
			            <li><a href="#">FAQs</a></li>
			            <li><a href="#">Webmaster</a></li>
			          </ul>
			        </div>
			      </div>
			      <div class="col-md-3 col-sm-6">
			        <!--Column1-->
			        <div class="footer-pad">
			          <h4>Heading 3</h4>
			          <ul class="list-unstyled">
			            <li><a href="#">Parks and Recreation</a></li>
			            <li><a href="#">Public Works</a></li>
			            <li><a href="#">Police Department</a></li>
			            <li><a href="#">Fire</a></li>
			            <li><a href="#">Mayor and City Council</a></li>
			            <li>
			              <a href="#"></a>
			            </li>
			          </ul>
			        </div>
			      </div>
			    	<div class="col-md-3">
			    		<h4>Follow Us</h4>
			            <ul class="social-network social-circle">
			             <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
			             <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
			            </ul>				
					</div>
			    </div>
				<div class="row">
					<div class="col-md-12 copy">
						<p class="text-center">&copy; Copyright 2018 - Company Name.  All rights reserved.</p>
					</div>
				</div>
			
			
			  </div>
			  </div>
		</footer>


        
    </body>

</html>
