
	 
 <?php
 	if(!empty($notification)):?>
   <div class="alert alert-warning alert-dismissible fade show" role="alert">
      	<?php echo $notification ?>
   		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <?php endif;

	if($alertConnexionFail){ // la première fois qu'on entre dans la page connexion, la variable est null, elle ne détient rien ("")
		echo $alertConnexionFail; // si la personne n'a pas pu se connecter, alors le message s'affiche.
	}
	?>
			
				<div id="login">
			        <h3 class="text-center text-white pt-5">Login form</h3>
			        <div class="container">
			            <div id="login-row" class="row justify-content-center align-items-center">
			                <div id="login-column" class="col-md-6">
			                    <div id="login-box" class="col-md-12">
			                        <form id="login-form" class="form" action="../Controller/AdminController.php?choix=verifConnexion" method="post">
			                            <h3 class="text-center text-info">Login</h3>
			                            <div class="form-group">
			                                <label for="username" class="text-info">nom d'utilisateur admin:</label><br>
			                                <input type="text" name="nameAdmin" id="nameAdmin" class="form-control">
			                            </div>
			                            <div class="form-group">
			                                <label for="password" class="text-info">Password:</label><br>
			                                <input type="password" name="password" id="password" class="form-control">
			                            </div>
			                            <div class="form-group">
			                                <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
			                                <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
			                            </div>
										<div class="form-group">
											<input type="submit" placeholder="valider"  class="input input-bordered font-rubik" required/>
										</div>
			                            <div id="register-link" class="text-right">
			                                <a href="../php/register.php" class="text-info">Register here</a>
			                            </div>
			                        </form>
			                    </div>
			                </div>
			            </div>
			        </div>
				</div>
		
		
		
	  
	  
	</body>
</html>

<