<!--=============== MAIN ===============-->
<section>
    <div class="tabs flex justify-center">
      <a id="1" class="tab tab-lg tab-bordered font-fredoka" href="./profil.phtml">Mes fiches</a>
      <a id="2" class="tab tab-lg tab-bordered font-fredoka tab-active" href="./profil2.phtml">Mes commentaires</a>
    </div>
  </section>

  <section>
    <div class="overflow-x-auto">
      <table class="table w-full">
        <thead>
          <tr>
            <th></th>
            <th class="font-fredoka">Titre de la fiche</th>
            <th class="font-fredoka">Catégorie</th>
            <th class="font-fredoka">Date</th>
            <th class="font-fredoka">Gestion</th>

          </tr>
        </thead>
        <tbody>
          <!-- row 1 -->
          <tr class="hover">
            <td></td>
            <td class="font-rubik">Problème</td>
            <td class="font-rubik">cat</td>
            <td class="font-rubik">10/11/2022</td>
            <td><input type="button" href="#" value="Modifier" class="btn btn-xs btn-primary font-rubik justify-center"></input><br><input type="button" href="#" value="Supprimer" class="btn btn-xs btn-primary font-rubik justify-center"></input></td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>